

const ThrowError = () => {
    throw new Error("The error has thrown.")
    return <></>
}
export default ThrowError